require flex
git-svn-id: https://powerman.googlecode.com/svn/branches/powerman-2.0@898 76eff002-5ed3-810f-47aa-be2f003abbef

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3313,6 +3313,11 @@ fi
 if test "$LEX" = :; then
   LEX=${am_missing_run}flex
 fi
+if test "$LEX" != "flex"; then
+  { { echo "$as_me:$LINENO: error: lex won't cut it, I need flex" >&5
+echo "$as_me: error: lex won't cut it, I need flex" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
