tidy up longopt handling add framework for genders support
git-svn-id: https://powerman.googlecode.com/svn/branches/powerman-2.0@900 76eff002-5ed3-810f-47aa-be2f003abbef

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PROJECT VERSION RELEASE build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE GCCWARN LN_S LEX LEXLIB LEX_OUTPUT_ROOT YACC WITH_GNU_LD_TRUE WITH_GNU_LD_FALSE CPP EGREP WITH_HTTPPOWER_TRUE WITH_HTTPPOWER_FALSE LIBFORKPTY LIBWRAP LIBREADLINE LIBCURL LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PROJECT VERSION RELEASE build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE GCCWARN LN_S LEX LEXLIB LEX_OUTPUT_ROOT YACC WITH_GNU_LD_TRUE WITH_GNU_LD_FALSE CPP EGREP WITH_HTTPPOWER_TRUE WITH_HTTPPOWER_FALSE LIBGENDERS LIBFORKPTY LIBWRAP LIBREADLINE LIBCURL LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -860,6 +860,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-httppower        Build httppower executable
+  --with-genders          Build genders support
 
 Some influential environment variables:
   CC          C compiler command
@@ -4394,7 +4395,7 @@ fi
 
 
 ##
-# Check for httppower
+# Check for httppower, genders
 ##
 
   echo "$as_me:$LINENO: checking for whether to build httppower executable" >&5
@@ -4431,6 +4432,111 @@ else
   WITH_HTTPPOWER_TRUE='#'
   WITH_HTTPPOWER_FALSE=
 fi
+
+
+  echo "$as_me:$LINENO: checking for whether to build genders support" >&5
+echo $ECHO_N "checking for whether to build genders support... $ECHO_C" >&6
+
+# Check whether --with-genders or --without-genders was given.
+if test "${with_genders+set}" = set; then
+  withval="$with_genders"
+   case "$withval" in
+        no)  ac_genders_test=no ;;
+        yes) ac_genders_test=yes ;;
+        *)   { { echo "$as_me:$LINENO: error: bad value \"$withval\" for --with-genders" >&5
+echo "$as_me: error: bad value \"$withval\" for --with-genders" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+
+
+fi;
+  echo "$as_me:$LINENO: result: ${ac_genders_test=no}" >&5
+echo "${ECHO_T}${ac_genders_test=no}" >&6
+
+  if test "$ac_genders_test" = "yes"; then
+     echo "$as_me:$LINENO: checking for genders_handle_create in -lgenders" >&5
+echo $ECHO_N "checking for genders_handle_create in -lgenders... $ECHO_C" >&6
+if test "${ac_cv_lib_genders_genders_handle_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgenders  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char genders_handle_create ();
+int
+main ()
+{
+genders_handle_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_genders_genders_handle_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_genders_genders_handle_create=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_genders_genders_handle_create" >&5
+echo "${ECHO_T}$ac_cv_lib_genders_genders_handle_create" >&6
+if test $ac_cv_lib_genders_genders_handle_create = yes; then
+  ac_have_genders=yes
+fi
+
+  fi
+
+  if test "$ac_have_genders" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_GENDERS 1
+_ACEOF
+
+     LIBGENDERS="-lgenders"
+     ac_with_genders=yes
+  else
+     LIBGENDERS=
+     ac_with_genders=no
+  fi
+
 
 
 ##
@@ -6138,6 +6244,7 @@ s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@WITH_HTTPPOWER_TRUE@,$WITH_HTTPPOWER_TRUE,;t t
 s,@WITH_HTTPPOWER_FALSE@,$WITH_HTTPPOWER_FALSE,;t t
+s,@LIBGENDERS@,$LIBGENDERS,;t t
 s,@LIBFORKPTY@,$LIBFORKPTY,;t t
 s,@LIBWRAP@,$LIBWRAP,;t t
 s,@LIBREADLINE@,$LIBREADLINE,;t t
