add /etc/powerman/stonith.conf support
git-svn-id: https://powerman.googlecode.com/svn/trunk@815 76eff002-5ed3-810f-47aa-be2f003abbef

diff --git a/scripts/stonith-powerman b/scripts/stonith-powerman
--- a/scripts/stonith-powerman
+++ b/scripts/stonith-powerman
@@ -3,21 +3,29 @@
 # External heartbeat STONITH module for powerman
 # (install as /usr/%{libdir}/stonith/plugins/external/powerman)
 #
-# XXX Note on excess paranoia:  Presumably heartbeat will verify any on|off 
-# operations by following it with a status operation, but we do the same
-# thing internally just to be sure, retrying once per second for 60 seconds
-# until we get the intended result.
+# Excess paranoia:  
+# Presumably heartbeat will verify any on|off operation by following it 
+# with a status operation, but we do the same thing internally just to 
+# be sure, retrying once per second for 60 seconds until we get the 
+# intended result.
 #
-# XXX Note on error handling:
-# We exit 1 on most errors.  This could be confused with a power-on result
+# Error handling:
+# We exit 1 on most errors.  This could be confused with a power=on result
 # from the status query.  It is unknown whether heartbeat takes note of
 # the exit value on other operations.
 #
+# Config file:
+# If the powerman daemon is running on a different node, you must create
+# /etc/powerman/stonith.conf and set POWERMAN_HOST appropriately.  
+# The config file will be sourced as a bash script.  Note that you may
+# have to alter your tcp_wrappers configuration to make this work.
 
 declare -r path_powerman=/usr/bin/powerman
 declare -r prog=stonith-powerman
-declare -r retry_secs=5
+declare -r retry_secs=60
 declare -r reset_delay_secs=2
+declare -r config_file=/etc/powerman/stonith.conf
+pmopts=""
 
 die()
 {
@@ -43,8 +51,8 @@ power_on()
     local stat
 
     while [ $secs -gt 0 ]; do
-        ${path_powerman} -1 $1 >/dev/null
-        stat=$(${path_powerman} -qx $1 | cut -d: -f2 | sed 's/[ ]*//')
+        ${path_powerman} ${pmopts} -1 $1 >/dev/null
+        stat=$(${path_powerman} ${pmopts} -qx $1 | cut -d: -f2 | sed 's/[ ]*//')
         if [ "${stat}" = "on" ]; then
             return 
         fi
@@ -61,8 +69,8 @@ power_off()
     local stat
 
     while [ $secs -gt 0 ]; do
-        ${path_powerman} -0 $1 >/dev/null
-        stat=$(${path_powerman} -qx $1 | cut -d: -f2 | sed 's/[ ]*//')
+        ${path_powerman} ${pmopts} -0 $1 >/dev/null
+        stat=$(${path_powerman} ${pmopts} -qx $1 | cut -d: -f2 | sed 's/[ ]*//')
         if [ "${stat}" = "off" ]; then
             return 
         fi
@@ -79,7 +87,7 @@ power_status()
     local stat
 
     while [ $secs -gt 0 ]; do
-        stat=$(${path_powerman} -qx $1 | cut -d: -f2 | sed 's/[ ]*//')
+        stat=$(${path_powerman} ${pmopts} -qx $1 | cut -d: -f2 | sed 's/[ ]*//')
         if [ "${stat}" = "off" ]; then
             exit 1
         fi
@@ -95,10 +103,18 @@ power_status()
 # Get host list
 power_hostlist()
 {
-    ${path_powerman} -lx
+    ${path_powerman} ${pmopts} -lx
 }
 
 [ $# = 1 ] || [ $# = 2 ] || usage
+
+if [ -f ${config_file} ]; then
+    source ${config_file}
+    if [ -n "$POWERMAN_HOST" ]; then
+        pmopts="${pmopts} -d $POWERMAN_HOST"
+    fi
+fi
+
 case $1 in
     gethosts)
         power_hostlist
